#!/bin/sh

DIRS=""

if [ -d "$HOME/.local/share/applications" ]; then
  DIRS="$DIRS $HOME/.local/share/applications"
fi
if [ -d "/usr/local/share/applications" ]; then
  DIRS="$DIRS /usr/local/share/applications"
fi
if [ -d "/usr/share/applications" ]; then
  DIRS="$DIRS /usr/share/applications"
fi


ENTRIES=$(find $DIRS |  grep "\.desktop$")
DESKTOP_FILE=$(printf '%s\n' "$ENTRIES"  | uniq | dmenu -d "$@")

if [ -n "$DESKTOP_FILE" ]; then

  DESKTOP_FILENAME=$(basename "$DESKTOP_FILE")

  if [ -n "$DESKTOP_FILENAME" ]; then
    echo "$DESKTOP_FILE"
    gtk-launch "$DESKTOP_FILENAME"
  fi
fi
